scheme = [
    ['Snout', 'EarL'],
    ['Snout', 'EarR'],
    ['Snout', 'Neck'],
    ['Neck', 'SpineL'],
    ['SpineL', 'TailBase'],
    ['TailBase', 'Tail1Q'],
    ['Tail1Q', 'TailMid'],
    ['TailMid', 'Tail3Q'],
    ['Tail3Q', 'TailTip'],
    ['ShoulderL', 'ElbowL'],
    ['ElbowL', 'WristL'],
    ['WristL', 'HandL'],
    ['ShoulderR', 'ElbowR'],
    ['ElbowR', 'WristR'],
    ['WristR', 'HandR'],
    ['SpineL', 'HipL'],
    ['HipL', 'KneeL'],
    ['KneeL', 'AnkleL'],
    ['AnkleL', 'FootL'],
    ['SpineL', 'HipR'],
    ['HipR', 'KneeR'],
    ['KneeR', 'AnkleR'],
    ['AnkleR', 'FootR']
]