scheme = [
    # left legs
    ['L1A', 'L1B'],
    ['L1B', 'L1C'],
    ['L1C', 'L1D'],
    ['L1D', 'L1E'],

    ['L2A', 'L2B'],
    ['L2B', 'L2C'],
    ['L2C', 'L2D'],
    ['L2D', 'L2E'],

    ['L3A', 'L3B'],
    ['L3B', 'L3C'],
    ['L3C', 'L3D'],
    ['L3D', 'L3E'],

    # right legs
    ['R1A', 'R1B'],
    ['R1B', 'R1C'],
    ['R1C', 'R1D'],
    ['R1D', 'R1E'],

    ['R2A', 'R2B'],
    ['R2B', 'R2C'],
    ['R2C', 'R2D'],
    ['R2D', 'R2E'],

    ['R3A', 'R3B'],
    ['R3B', 'R3C'],
    ['R3C', 'R3D'],
    ['R3D', 'R3E']
]