scheme = [
    ['nose', 'L-ear'],
    ['nose', 'R-ear'],
    ['nose', 'neck'],
    ['neck', 'spine-mid'],
    ['spine-mid', 'tail-base'],
    ['tail-base', 'tail-1/3'],
    ['tail-1/3', 'tail-2/3'],
    ['tail-2/3', 'tail-end'],

    ['spine-mid', 'LF-shoulder'],
    ['LF-shoulder', 'LF-elbow'],
    ['LF-elbow', 'LF-wrist'],
    ['LF-wrist', 'LF-index-base'],
    ['LF-index-base', 'LF-index'],
    ['LF-wrist', 'LF-middle'],
    ['LF-wrist', 'LF-ring'],
    ['LF-wrist', 'LF-pinkie-base'],
    ['LF-pinkie-base', 'LF-pinkie'],

    ['spine-mid', 'RF-shoulder'],
    ['RF-shoulder', 'RF-elbow'],
    ['RF-elbow', 'RF-wrist'],
    ['RF-wrist', 'RF-index-base'],
    ['RF-index-base', 'RF-index'],
    ['RF-wrist', 'RF-middle'],
    ['RF-wrist', 'RF-ring'],
    ['RF-wrist', 'RF-pinkie-base'],
    ['RF-pinkie-base', 'RF-pinkie'],

    ['tail-base', 'LH-hip'],
    ['LH-hip', 'LH-knee'],
    ['LH-knee', 'LH-wrist'],
    ['LH-wrist', 'LH-thumb-base'],
    ['LH-thumb-base', 'LH-thumb'],
    ['LH-wrist', 'LH-index'],
    ['LH-wrist', 'LH-middle'],
    ['LH-wrist', 'LH-ring'],
    ['LH-wrist', 'LH-pinkie-base'],
    ['LH-pinkie-base', 'LH-pinkie'],

    ['tail-base', 'RH-hip'],
    ['RH-hip', 'RH-knee'],
    ['RH-knee', 'RH-wrist'],
    ['RH-wrist', 'RH-thumb-base'],
    ['RH-thumb-base', 'RH-thumb'],
    ['RH-wrist', 'RH-index'],
    ['RH-wrist', 'RH-middle'],
    ['RH-wrist', 'RH-ring'],
    ['RH-wrist', 'RH-pinkie-base'],
    ['RH-pinkie-base', 'RH-pinkie']
]